- app/models/comapny.rb
- app/models/company.rb
- app/models/contact.rb
- app/models/event.rb
- app/models/note.rb
- app/models/todo.rb
- db/migrate/20240820013603_create_companies.rb
- db/migrate/20240820013604_create_contacts.rb
- db/migrate/20240820014442_create_events.rb
- db/migrate/20240820020210_create_todos.rb
- db/migrate/20240820020311_create_notes.rb
- db/schema.rb
- test/models/company_test.rb
@jpblicer created models associations and fixed some migrations
> created models associations and fixed migrations

- config/routes.rb
> setup routes

- Gemfile
- Gemfile.lock
- app/models/todo.rb
- db/migrate/20240820034723_add_email_to_contacts.rb
- db/migrate/20240820034905_add_country_to_contacts.rb
- db/schema.rb
- db/seeds.rb
@Paretooptimal22 pls review
Added the seeds
> seeded the db

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
-set the font size of html to 62.5% to make 1rem = 10px
-reset the margin padding text decoration and borderbox in the bootsrap variable
-styled the navbar
> styled mobile navbar

- app/controllers/contacts_controller.rb
- app/views/contacts/_contact_form.html.erb
- app/views/contacts/new.html.erb
- test/controllers/contacts_controller_test.rb
created controller for contacts and simple form:
> created contacts controller and form to add new contact

- app/controllers/contacts_controller.rb
- app/views/contacts/show.html.erb
- config/routes.rb
- test/controllers/contacts_controller_test.rb
@Paretooptimal22 
added the controller and view for the show page 
#sopretty
> show page controller and view

- app/assets/stylesheets/components/_bottom_navbar.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar.scss
- app/views/layouts/application.html.erb
- app/views/shared/_bottom_navbar.html.erb
-added hover effects on the top nav bar
-added shadow effects on the top nav bar
-created bottom nav bar with hover effects
> created bottom nav

- app/views/todos/new.html.erb
fixed input label on todo to ask for todo name instead of task name
> fixed label on the todoname to reflect todo

- app/controllers/contacts_controller.rb
@jpblicer I removed the raises in the contacts controller
> removed raises from the contacts controller

- app/assets/stylesheets/components/_bottom_navbar.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/views/layouts/application.html.erb
> fixed errors

- app/assets/stylesheets/components/_navbar.scss
- app/javascript/controllers/navigation_controller.js
- app/views/shared/_bottom_navbar.html.erb
- app/views/shared/_navbar.html.erb
-added hover effects on the navbar items
-added a  drop down
-added links to drop down items
-added hover effects on drop down items
- moved the home button position in the bottom navbar
> added dropdown to navbar

- db/seeds.rb
Changed .all.sample to use random to have better performance
> fixed seeds to respect polymorphic relation. 

- app/views/contacts/show.html.erb
@Paretooptimal22  sensei, please review
contacts - show page:
- made the fields optional so contacts with missing fields will still show
> contact show page - made all the detai fields optional

- app/controllers/companies_controller.rb
- app/views/companies/show.html.erb
- test/controllers/companies_controller_test.rb
@Paretooptimal22 project sensei, please review
(no merging conflicts)
Adding company show page
- created the company controller and view folder
- created company show page (copy of contact show page)
- displayed company avatar
> added company show page with company avatar

- app/controllers/contacts_controller.rb
- app/controllers/notes_controller.rb
- app/views/contacts/show.html.erb
- app/views/notes/_add_note.html.erb
- app/views/notes/_notes.html.erb
@jpblicer added the notes form to the contact show
> added note form to the contact show

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_no_data.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/pages/_contact-show.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/contacts/show.html.erb
- app/views/shared/_no_data.html.erb
> styled the contact show

- .gitignore
- Gemfile
- Gemfile.lock
- app/controllers/contacts_controller.rb
- app/models/contact.rb
- app/views/contacts/_contact_form.html.erb
- app/views/contacts/show.html.erb
- config/environments/development.rb
- config/environments/production.rb
- config/storage.yml
- db/migrate/20240821083213_create_active_storage_tables.active_storage.rb
- db/schema.rb
@Paretooptimal22 please review, it's pretty sweet
Added image upload functionality in form
> Form image upload

- app/assets/config/manifest.js
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_bottom_navbar.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/config/_base.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_fonts.scss
set the css variables and changed a few color schemes and changed font family for body and headings
> Set css variables

- app/views/contacts/show.html.erb
- app/views/notes/_add_note.html.erb
- app/views/notes/_notes.html.erb
- app/views/todos/_todo_form.html.erb
- app/views/todos/_todos.html.erb
@jpblicer styled the contact show todos/notes
> Style contact show todo notes

- app/controllers/pages_controller.rb
oldest items are at the top instead of bottom now
> remove reverse so that upcoming items are from the nearest date

- app/assets/stylesheets/config/_base.scss
- app/controllers/todos_controller.rb
- app/views/contacts/show.html.erb
- app/views/todos/_todo_form.html.erb
fix todo redirect to avoid going to a new page causing breakage. 
Also fix css on body container to calc the nav-bar bottom height of 95px to avoid bottom bar overlapping content and also changed height to min-height so background covers entire view
> General Fixes - body css, todo date error breakage

- app/assets/stylesheets/components/_no_data.scss
- app/controllers/companies_controller.rb
- app/controllers/contacts_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/todos_controller.rb
- app/views/contacts/new.html.erb
- app/views/shared/_navbar.html.erb
- app/views/todos/_todo.html.erb
- app/views/todos/new.html.erb
-Changed the navname dynamically and put a fallback as emptystring.
-removed redundancy in navname and title of the content.
-added instance variable @page_title to each controller that has its own view
> Change navname dynamically

- app/views/contacts/show.html.erb
- app/views/notes/_notes.html.erb
- app/views/todos/_todos.html.erb
@yutaasakura96 in the contact show page, updated:
- details icons and container
- todos and notes
> Style contact show details

- app/controllers/events_controller.rb
- app/models/event.rb
- app/views/events/new.html.erb
- test/controllers/events_controller_test.rb
can add events and tag multiple contacts and companies with tom select
> Event controller new and create

- app/assets/stylesheets/components/_contact_form.scss
- app/assets/stylesheets/components/_index.scss
- app/javascript/controllers/tom_select_controller.js
- app/views/contacts/_contact_form.html.erb
@Paretooptimal22  please review
(no mergin conflicts)
contact form styling
- change input boxes
- fixed styling of company select box
// still to work on font size issue
> styling of the contact form - still wip

- app/assets/stylesheets/config/_base.scss
@jpblicer  pls review
fixed background height
> background-fix

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_contact_index.scss
- app/assets/stylesheets/pages/_index.scss
- app/javascript/controllers/navigation_controller.js
- app/views/contacts/index.html.erb
- app/views/shared/_navbar.html.erb
- app/views/todos/new.html.erb
- db/seeds.rb
-Fixed navbar title to be removed dynamically when plus button is clicked
-fixed the error with new to do form
-removed the image for contacts inside db:seed
-created contacts index page
> Contact index

- app/assets/stylesheets/config/_base.scss
- app/assets/stylesheets/config/_fonts.scss
- app/assets/stylesheets/pages/_contact_index.scss
- app/views/contacts/index.html.erb
-changed the background color.
-styled contact page
-made the contacts in contact page clickable and redirect to that contact's corresponding show page
> styled the contact page

- app/views/pages/_dashboard_counters.html.erb
- app/views/pages/_upcoming_eventstodos.html.erb
- app/views/pages/home.html.erb
broken dashboard into components. added overflow and height limit on the upcoming todos. added shadow and adjusted colors and font boldness.
> dashboard components and css

- app/assets/stylesheets/config/_base.scss
- app/views/contacts/_contact.html.erb
- app/views/contacts/_contact_details.html.erb
- app/views/contacts/show.html.erb
- app/views/notes/_notes.html.erb
- app/views/todos/_todos.html.erb
updated styling on the contacts show
- background color matches figma now (this was a global variable change)
- included company name and avatar to the details section (included conditional if there is no name or avatar)
- moved the icons closer together
- added height limits to the todo and notes
> updated contacts show styling

- app/controllers/pages_controller.rb
- app/views/pages/_dashboard_counters.html.erb
- app/views/pages/home.html.erb
commented out all the event parts of the dashboard and added the most recently updated contacts
> Dashboard most contacted

- app/views/contacts/_contact.html.erb
- app/views/pages/home.html.erb
set the dashboard and show page cloudinary images with gravity of face and the propery dimensions and overflow
> Contact avatar set size

- app/assets/stylesheets/components/_contact_form.scss
- app/views/contacts/show.html.erb
added some padding and removed the border
> removed border and added padding to form area

- app/assets/stylesheets/components/_avatar.scss
- app/views/contacts/_contact.html.erb
@jpblicer pls review
contact show page
- fixed the company avatar to display properly
> Company avatar

- app/views/contacts/show.html.erb
removed shadow in the list container
> removed some shadow in contact show

- app/views/contacts/_contact_form.html.erb
@Paretooptimal22  please review 🙏 
New contact form page
- fixed issue with different form displaying
> fixed font-size issue

- app/views/pages/_dashboard_upcoming.html.erb
> dashboard minor color changes

- app/assets/stylesheets/config/_base.scss
> remove min-height

- db/seeds.rb
drop everything to seed bespoke data after
> seed comments

- app/views/contacts/_contact.html.erb
- app/views/contacts/_contact_details.html.erb
contacts show was missing the else statement. added it to show the company icon if there is no company avatar
> added else conditional for the company avatar

- app/controllers/companies_controller.rb
- app/views/companies/index.html.erb
Contact index and basic styling done
> add company index and layout and style bootstrap

- app/controllers/companies_controller.rb
- app/models/company.rb
- app/views/companies/index.html.erb
- app/views/companies/new.html.erb
- app/views/companies/show.html.erb
- app/views/contacts/_contact.html.erb
> Companies new create images and index

- app/controllers/contacts_controller.rb
- app/services/extract_business_card.rb
- app/views/contacts/_contact_form.html.erb
- app/views/contacts/edit.html.erb
- config/routes.rb
-adding business card will now redirect the page to the edit page 
-added routes for contact edit/update
-updated the instructions of the AI model to extract also emails from the  business card
-made the edit page optionally show adding business card functionality if it already has one attached for better UI/UX
-fixed the postition of the add avatar functionality of the contact form
> -added edit/update contact to improve functionality of ocr.

- app/controllers/contacts_controller.rb
- app/views/contacts/show.html.erb
> edit icon linked to edit contact path

- app/javascript/controllers/contact_form_controller.js
- app/views/contacts/_contact_form.html.erb
-added stimulus controller for contact new form
-dynamically shows the extract data btn based on if there is a business card attached by using javascript.
> Fix extract btn in contact new

- app/assets/stylesheets/pages/_company_show.scss
- app/assets/stylesheets/pages/_index.scss
- app/controllers/companies_controller.rb
- app/controllers/todos_controller.rb
- app/views/companies/_company_lg_avatar.html.erb
- app/views/companies/show.html.erb
- app/views/contacts/show.html.erb
- app/views/notes/_notes_company.html.erb
- app/views/todos/_todos_company.html.erb
> styled the company show

- app/assets/stylesheets/pages/_event_index.scss
- app/controllers/event_contacts_controller.rb
- app/controllers/events_controller.rb
- app/views/contacts/_contact.html.erb
- app/views/event_contacts/create.html.erb
- app/views/events/index.html.erb
- config/routes.rb
- test/controllers/event_contacts_controller_test.rb
-added assign contact to an event functionality in the contact show page
-contacts that are assigned to an event will now be visible in the events index page
> Implemented assign contact to an event functionality

- app/services/extract_business_card.rb
-improved ai model to be able to read japanese business cards and also translate it to english
> updated ai model

- app/controllers/contacts_controller.rb
-updated the contact controller to fix the bug where in the contact will still be created even if the AI parsing fails.
> fixed the ai contact creation bug

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_todo_status_buttons.scss
- app/controllers/todos_controller.rb
- app/models/todo.rb
- app/views/todos/_todo_upcoming.html.erb
- app/views/todos/index.html.erb
@yutaasakura96 pls approve my humble pull request
pushing my work on the todo index page now to be up to date with the code base
done:
- listing all todo's
- added filter for todos
to do:
- style filter buttons
- show contact name with each todo
- add option to mark todo's as done
> push of work on todo index so far

- app/views/contacts/_contact_details.html.erb
-fixed the contact show page bug where in the icon shows even if the field related to it is empty.
-Added the country and appended it to the address to make the page look cleaner.
> fixed the contact show bug

- app/views/events/index.html.erb
> arrow stays at the bottom on expanded card

- app/views/contacts/show.html.erb
- app/views/events/_events.html.erb
> contact show displays contact events

- app/views/todos/_todo_upcoming.html.erb
@Paretooptimal22 pls approve
fixed a bug
> fixed bug in displaying contact

- app/views/companies/_companies_index_icons.html.erb
- app/views/companies/index.html.erb
- app/views/contacts/index.html.erb
company index and contact index styling now matching:
> Company index css

- app/views/companies/show.html.erb
- app/views/contacts/show.html.erb
> update todos and events spelling on both contact and company show

- app/views/contacts/_contact.html.erb
> contact show now has company avatar and links to the company show

- app/views/events/_events.html.erb
- app/views/events/index.html.erb
> on events index showing contact avatars on expand

- app/views/pages/_dashboard_upcoming_cards.html.erb
text no longer overflows on the dashboard
> Text overflow

- app/assets/stylesheets/components/_todo_status_buttons.scss
- app/controllers/todos_controller.rb
- app/views/shared/_bottom_navbar.html.erb
- app/views/todos/_todo_upcoming.html.erb
- app/views/todos/index.html.erb
@Paretooptimal22 plllsss reviewww
lots of styling
> todo display page styling

- app/controllers/pages_controller.rb
Dashboard upcoming will only show todos and events that have not passed
> Events and Todos no longer show up if passed current date

- app/controllers/events_controller.rb
- app/views/events/_event_filters.html.erb
- app/views/events/index.html.erb
can filter events but upcoming, past, and all
> filters for events added

- app/views/companies/_company_contacts.html.erb
- app/views/companies/show.html.erb
Related contacts added to company show and deals with overflow:
> Contacts company show

- app/views/contacts/_contact.html.erb
fixed the bug by wrapping with if @contact.company
> you can add and view a contact without a company

- app/controllers/todos_controller.rb
- app/views/pages/_dashboard_recentlycontacted.html.erb
- app/views/pages/_dashboard_upcoming_filters.html.erb
- app/views/todos/index.html.erb
Assignees: yutaasakura96
yutaasakura96
[Dashboard - get rid of the Upcoming Text](https://github.com/jpblicer/rails-prm/issues/235)
Click a value to filter the view
Assignees: yutaasakura96
yutaasakura96
[Dashboard - Remove Image border on avatar and add more shadow](https://github.com/jpblicer/rails-prm/issues/236)
Click a value to filter the view
Assignees: yutaasakura96
yutaasakura96
[ToDos Index - Rename page title to "To Dos"](https://github.com/jpblicer/rails-prm/issues/240)
> Fix styling issues

- app/controllers/events_controller.rb
- app/views/events/new.html.erb
> new event page update title and form order

- app/assets/stylesheets/pages/_company_index.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/companies/index.html.erb
Matched company index styling based on what we have for the contact index
> match the company index style to that of contact index

- app/assets/stylesheets/config/_base.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/views/contacts/_contact_form.html.erb
- app/views/pages/_dashboard_upcoming_cards.html.erb
- app/views/todos/_todo_upcoming.html.erb
[New contact - Move Avatar Upload to Details Section](https://github.com/jpblicer/rails-prm/issues/242)
Click a value to filter the view
Assignees: yutaasakura96
yutaasakura96
[Get rid of Icons on Todos and Events](https://github.com/jpblicer/rails-prm/issues/234)
Click a value to filter the view
Assignees: yutaasakura96
yutaasakura96
[increase font size on the todos and notes](https://github.com/jpblicer/rails-prm/issues/194)
Click a value to filter the view
Assignees: yutaasakura96
yutaasakura96
[Whole App - Double App Font Size](https://github.com/jpblicer/rails-prm/issues/231)
Click a value to filter the view
> Fix styling issues v2

- app/models/event.rb
> added dependent destory in event model

- app/models/user.rb
- app/views/shared/_bottom_navbar.html.erb
> Notifications

- app/controllers/todos_controller.rb
- app/views/todos/_todos.html.erb
- app/views/todos/index.html.erb
@jpblicer  pls review
todo index -  heroku 500 error debug
> todo index 500 error

- app/views/shared/_navbar.html.erb
> we settled on this type of approach

- app/assets/stylesheets/components/_contact_form.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/views/companies/new.html.erb
- app/views/contacts/_contact_form.html.erb
- app/views/events/_event_form.html.erb
- app/views/todos/_todo_form.html.erb
-fixed forms styling.
-styling on new events not working??? please check.
> Fix forms styling

- app/views/events/index.html.erb
-added links to avatars in the events index
> events contact avatars now links to contact show page

- app/views/events/index.html.erb
Event index page cards now show the company in addition to contacts
> Event index dropdown company

- app/controllers/todos_controller.rb
- app/javascript/controllers/todo_controller.js
- app/models/todo.rb
- app/views/todos/_todos.html.erb
> Todo status

- app/views/companies/_company_lg_avatar.html.erb
- app/views/contacts/_contact_details.html.erb
- app/views/events/index.html.erb
addresses in the app open to google maps on click with the address (and country if applicable as the query)
> Address link google maps

- app/views/shared/_bottom_navbar.html.erb
in the bottom navbar html.erb, i wrapped the notification badge with an if current_user
> added if current user to the bottom bavbar html

- app/controllers/companies_controller.rb
> company page title no longer is the company name

- app/assets/stylesheets/components/_dashboard_buttons.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_todo_status_buttons.scss
- app/views/events/_event_filters.html.erb
- app/views/pages/_dashboard_upcoming_filters.html.erb
- app/views/todos/index.html.erb
@Paretooptimal22 pls review
- made button width equal
- worked on the button colors
> standardized button width

- app/controllers/events_controller.rb
- app/models/event.rb
- app/services/extract_event_info.rb
- app/views/events/edit.html.erb
- app/views/events/new.html.erb
- config/routes.rb
-added new AI model to automate inputing fields on the event date. it will take the name, address, start date, end date.
-can be improved with more fields
-still needs polishing using stimulus JS for better UI/UX
> New ai model for new event creation

- Gemfile
- app/views/companies/_companies_index_icons.html.erb
- app/views/companies/_company_lg_avatar.html.erb
- app/views/contacts/_contact.html.erb
- app/views/contacts/_contacts_index_icons.erb
Fixed the company show and made links work by changing how we test for proper links
> error was with how we were testing for linkedin

- app/views/contacts/_contact_form.html.erb
- app/views/events/new.html.erb
-fixed the styling of new event form to match all the other forms
> fixed new event form styling

- app/views/contacts/_contact_form.html.erb
the submit button is now outside the form
> fixed the position of the submit btn

- app/views/companies/new.html.erb
-the new company submit btn is now outside the form
> fixed the new company submit btn position

- app/assets/stylesheets/components/_navbar.scss
-set the navbar font size back to its original size
> fixed the navbar fontsize

- app/views/shared/_bottom_navbar.html.erb
notification will not show if there is no todo or event for the current date
> hide notification if there is zero

- app/controllers/notifications_controller.rb
- app/javascript/controllers/notification_controller.js
- app/views/shared/_bottom_navbar.html.erb
- config/routes.rb
- test/controllers/notifications_controller_test.rb
Dynamically updates the notification count without requiring a page reload using stimulus and ajax.
> fixed notification rendering

- app/views/contacts/_assign_contact_form.html.erb
- app/views/notes/_add_note.html.erb
- app/views/todos/_todo_form.html.erb
Fixed all the forms on contact show
> fixed forms on contact show

- app/views/notes/_notes.html.erb
- app/views/todos/_todos.html.erb
> matched the styling of notes, todos, events on contact show

- app/views/companies/_companies_index_icons.html.erb
- app/views/companies/_company_lg_avatar.html.erb
- app/views/contacts/_contact.html.erb
temporarily blocked linkedin url function
> comment out the linkedin HHTP URI

- app/views/events/index.html.erb
@yutaasakura96 pls review
event card. moved the address down in the expandable box
> event-hide-address

- app/controllers/todos_controller.rb
- app/javascript/controllers/todo_controller.js
- app/views/contacts/show.html.erb
- app/views/todos/_todos.html.erb
- config/routes.rb
@Paretooptimal22 pls review
- changing todo status will actually be saved now
- todos that are archived will disappear without a page reload
> todos are archiveable now

- app/controllers/events_controller.rb
- app/views/events/edit.html.erb
@jpblicer doug fixed contacts to show in the new event form
> doug magic

- app/assets/stylesheets/components/_todo_status_buttons.scss
- app/javascript/controllers/todo_controller.js
- app/views/shared/_navbar.html.erb
- app/views/todos/_todo.html.erb
- app/views/todos/_todo_upcoming.html.erb
- app/views/todos/index.html.erb
fixed HTML markup and bugs of todos list
> complete overhaul of todos index

- app/views/todos/_todo.html.erb
- app/views/todos/_todo_form.html.erb
fixed the new to do page styling by adding bg padding and shadow
> New todo page fix

- app/controllers/todos_controller.rb
- app/javascript/controllers/todo_controller.js
- app/views/todos/index.html.erb
- config/routes.rb
changing the status of the todo will now remove that todo
> added remove todo by status functionality

- app/views/pages/_dashboard_recentlycontacted.html.erb
fixed the spacing and separated the first and last name to avoid overlapping names
> fixed the upcoming contacts

- app/views/pages/_dashboard_recentlycontacted.html.erb
Reverts jpblicer/rails-prm#340
> Revert "fixed the upcoming contacts"

- app/controllers/todos_controller.rb
- app/javascript/controllers/todo_controller.js
- app/views/todos/index.html.erb
- config/routes.rb
Reverts jpblicer/rails-prm#339
> Revert "added remove todo by status functionality"

- app/views/todos/_todo.html.erb
- app/views/todos/_todo_form.html.erb
Reverts jpblicer/rails-prm#338
> Revert "New todo page fix"

- app/controllers/todos_controller.rb
- app/views/companies/show.html.erb
- app/views/contacts/_contact_todos_notes_cards.html.erb
- app/views/contacts/show.html.erb
- app/views/notes/_note.html.erb
- app/views/notes/_notes.html.erb
- app/views/pages/_dashboard_upcoming_cards.html.erb
- app/views/todos/_todo.html.erb
- app/views/todos/_todo_upcoming.html.erb
- app/views/todos/_todos.html.erb
- app/views/todos/index.html.erb
Reverts jpblicer/rails-prm#335
> Revert "Bug fixing"

- app/controllers/events_controller.rb
- app/views/events/edit.html.erb
Reverts jpblicer/rails-prm#326
> Revert "doug magic"

- app/controllers/todos_controller.rb
- app/javascript/controllers/todo_controller.js
- app/views/contacts/show.html.erb
- app/views/todos/_todos.html.erb
Reverts jpblicer/rails-prm#324
> Revert "todos are archiveable now"

- app/controllers/todos_controller.rb
- app/javascript/controllers/todo_controller.js
- app/views/contacts/show.html.erb
- app/views/todos/_todo_upcoming.html.erb
- app/views/todos/_todos.html.erb
Reverts jpblicer/rails-prm#351
> Revert "Revert "todos are archiveable now""
